import Head from 'next/head'
import Features from '../components/features/features'
import Footer from '../components/footer/footer'
import Header from '../components/header/header'
import HomeHero from '../components/home-hero/home-hero'
import Steps from '../components/steps/steps'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>ThyFlow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <HomeHero />
        <Features />
        <Steps />
      </main>
      <Footer/>
    </>
  )
}
